**ATTRIBUTES

+ AET: (continuous), cost
+ CRU: (integer), cost
+ I: [1, 2], gain
+ Class: [1, 2, 3], gain, decision

decision: Class

**PREFERENCES

AET: cost
CRU: cost
I: gain
Class: gain

**EXAMPLES

1.0, 1, 2, 3
3.0, 1, 2, 3
1.5, 3, 2, 3
4.7, 2, 2, 2
4.0, 3, 2, 2
2.2, 4, 1, 2
5.1, 2, 1, 1
3.6, 4, 2, 1
6.0, 2, 1, 2
5.0, 5, 1, 2
5.5, 4, 1, 2
10.0, 4, 1, 1
9.1, 6, 1, 1
5.0, 7, 1, 1
4.2, 5, 1, 1
8.0, 4, 1, 1
8.5, 4, 1, 1
9.0, 4, 1, 1
8.3, 4, 1, 1

**END
