**ATTRIBUTES

+ Pair_of_examples: (numbercoded) (pair), none, description
+ diff_x: (integer), gain
+ diff_y: (integer), gain
+ Relation: (continuous), gain, decision

decision: Relation

**PREFERENCES

Pair_of_examples: none
diff_x: gain
diff_y: gain
Relation: gain

**EXAMPLES

{1, 2}, 4, -4, 0.0
{2, 1}, -4, 4, -1.0
{1, 3}, 8, -5, -1.0
{1, 1}, 0, 0, 0.0
{2, 2}, 0, 0, 0.0
{3, 3}, 0, 0, 0.0

**END
