**ATTRIBUTES

+ Pair_of_examples: (numbercoded) (pair), none, description
+ x: [_8, _7, _6, _2, 2] (pair), gain
+ y: [_2, 2, 3, 4, 5] (pair), gain
+ Relation: (continuous), gain, decision

decision: Relation

**PREFERENCES

Pair_of_examples: none
x: gain
y: gain
Relation: gain

**EXAMPLES

{1, 2}, {2, _2}, {_2, 2}, 0.0
{2, 1}, {_2, 2}, {2, _2}, -1.0
{1, 3}, {2, _6}, {_2, 3}, -1.0
{1, 1}, {2, 2}, {_2, _2}, 0.0
{2, 2}, {_2, _2}, {2, 2}, 0.0
{3, 3}, {_6, _6}, {3, 3}, 0.0

**END
